In [1]:
import numpy as np

In [32]:
a = np.zeros((7,1))
print(a)


[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [50]:
a = np.full((7,1),'la')
print(a)

[['la']
 ['la']
 ['la']
 ['la']
 ['la']
 ['la']
 ['la']]


In [ ]:
a = np.arange()

In [ ]:
a = ['la',]

In [47]:
# a = np.zeros((3,1))
# c = np.append(a,[0.],axis=0)
b = [[0,0,0],[1,1,1,1],[2,2,2,2,2]]
b = np.asarray(b)
for x in range(len(b)):
    b[x] = np.asarray(b[x])

In [48]:
a = np.zeros((3,1))
b = np.zeros((3,1))
for x in range(4):
    np.append()

array([array([0, 0, 0]), array([1, 1, 1, 1]), array([2, 2, 2, 2, 2])],
      dtype=object)

In [25]:
a = np.array([1,2,3])
b =  np.array([1,2,3])
c = a+b
print(c)

[2 4 6]


In [29]:
a = np.array([[0],[0],[0]])
print(a)
for x in range(len(a)):
    a[x] = 1
print(a)

[[0]
 [0]
 [0]]
[[1]
 [1]
 [1]]


In [18]:
a = np.array([1,2,3])
b = a
for x in range(7):
    b = np.concatenate((b,a),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [19]:
a = [1,0,-1]

In [20]:
b=[np.sin(x) for x in a]

In [21]:
b

[0.8414709848078965, 0.0, -0.8414709848078965]

In [22]:
a = np.array([1,0,-1])
b = np.sin(a)

In [23]:
b

array([ 0.84147098,  0.        , -0.84147098])